### PR TITLE
Added a way to signify deploys

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Our ruby library has this available, and I think it would be really cool if the PHP one had it too.

It would be really nice to just be able to write `Bugsnag::deploy()` in Laravel, and that would notify Bugsnag of the deploy.

### CODE REVIEW

**Comment by kattrali** [comment]
This is a great idea! Very ergonomic for the framework libraries to use too. 

One concern though is that it probably shouldn’t be in the `Client` since we don’t want people arbitrarily or accidentally sending deploy notifications from applications. Maybe we could have a separate separate `Deploy` class which has a `HttpClient`. Then usage would be something like `Bugsnag::Deploy::send(…)`

**Comment by GrahamCampbell** [comment]
Maybe, but having a separate class here would mean a lot lot more code. The current class is called Client, not Notifier.

**Comment by GrahamCampbell** [comment]
Having this here also has the advantage that when people set the release stage in their bootstrapping process (such as in the boot method in a laravel service provider) all this stuff makes it into the deploy information.

**Comment by kattrali** [comment]
That’s true. It makes sense to do this in a way that allows us to capture as many of the deployment fields as possible without additional overhead. Rolling with it. 🚄

**Comment by GrahamCampbell** [comment]
:D

**Comment by morloderex** [comment]
Curios does this support svn repos which is protected with a username or a password?

**Comment by GrahamCampbell** [comment]
It specifically only supports github.com at the moment.

**Comment by GrahamCampbell** [comment]
We only use the repository url in order to link you to your code from app.bugsnag.com. You can still use the deployment API if you don't use GitHub, just that feature in the dashboard will be unavailable. All other features will still work just the same.

**Pull request merged**
