### PR TITLE
Speed up error handler

### PR DESCRIPTION
**Pull request by snmaynard**
The reflection we are using here is reducing performance. We should also long term remove the proxy method we have from Client to Config as it adds an unacceptable performance overhead.

This is untested.

### CODE REVIEW

**Comment by loopj** [comment]
LGTM, agree on removing reflection completely too.

**Comment by thedotedge** [comment]
@GrahamCampbell to add more context, performance hit can be quite significant for some scenarios. This is a trace from php 7.1 where you can see severe impact:
image

**Comment by GrahamCampbell** [comment]
@thedotedge I find that Backfire tends to exaggerate the cost of lots of small functions calls, compared to the actual runtime when the profiler is turned off. In particular, I found this when profiling the Laravel container, where Blackfire said it was using half the CPU time. How significant does this compare to other code. It is called 7900 times, so it's taking way less than 0.01ms per time?

**Comment by snmaynard** [comment]
In that screenshot its not showing the Bugsnag\Client::shouldIgnoreErrorCode call which is the bit that this would remove IIRC

**Comment by thedotedge** [comment]
@snmaynard yep, but you have a full trace :)

**Comment by thedotedge** [comment]
Guys, 10 days after PR was open and still no release? 😢

**Comment by thedotedge** [comment]
ping :)

**Pull request merged**
