### PR TITLE
Add .gitattributes file

### PR DESCRIPTION
**Pull request by vinkla**
This will allow us to exclude files in production with the `--prefer-dist` flag.

### CODE REVIEW

**Comment by kattrali** [comment]
Thank you for the contribution, @vinkla. Somehow I missed this PR when writing the `.gitattributes` file, though there should be one in place now.

**Comment by vinkla** [comment]
Okay, great. Maybe you could use the one in my PR? The current one is broken.

**Comment by kattrali** [comment]
@vinkla How is it broken?

**Comment by vinkla** [comment]
The phpunit line. Why does it only exclude three files?

**Comment by vinkla** [comment]
If you compare the current one with this PR you will see that this PR includes more files.

**Comment by kattrali** [comment]
The example and testing files could conflict with development environments. Not so much the readme and license, et cetera.

**Comment by vinkla** [comment]
Yeah but this doesn't matter for development environment. These files will only be ignored in production. Which is good. Saves space.

**Comment by GrahamCampbell** [comment]
We'll get this sorted for you now. :)

**Comment by vinkla** [comment]
:+1:

**Pull request closed without merging**
